# Use a nice font that we can install everywhere
font:
  normal:
    family: Source Code Pro

  size: 12

# No need for bold when using bright colors
draw_bold_text_with_bright_colors: false

# Hybrid colors
colors:
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'

  normal:
    black:   '0x282a2e'
    red:     '0xa54242'
    green:   '0x8c9440'
    yellow:  '0xde935f'
    blue:    '0x5f819d'
    magenta: '0x85678f'
    cyan:    '0x5e8d87'
    white:   '0x707880'

  bright:
    black:   '0x373b41'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xc5c8c6'

# Hide the mouse when we're not using it
mouse:
  hide_when_typing: true

# Add back support for key binds I'm used to because of other emulators
key_bindings:
  - { key: Return, mods: Command, action: ToggleFullscreen }

#debug:
  # Display the time it takes to redraw each frame.
  #render_timer: false

  # Keep the log file after quitting Alacritty.
  #persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  #log_level: Warn

  # Print all received window events.
  #print_events: false

  # Record all characters and escape sequences as test data.
  #ref_test: false
