# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/sd-card/sd-image-aarch64.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Uncompressed so it's faster to rebuild/reflash while iterating.
  sdImage.compressImage = false;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
    "uas"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # The sd-image module (imported by ./default.nix) provides its own
  # fileSystems."/" — don't duplicate it here or the build conflicts.
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
