# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.installDeviceTree = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.deviceTree = {
    enable = true;
    name = "qcom/sc8280xp-lenovo-thinkpad-x13s.dtb";
  };

  boot.kernelParams = [
    "clk_ignore_unused"
    "pd_ignore_unused"
    "arm64.nopauth"
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "usb_storage"

    "i2c-core"
    "i2c-hid"
    "i2c-hid-of"
    "i2c-qcom-geni"
    #"pcie-qcom"
    "phy-qcom-qmp-combo"
    "phy-qcom-qmp-pcie"
    "phy-qcom-qmp-usb"
    "phy-qcom-snps-femto-v2"
    "phy-qcom-usb-hs"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # There's a bug somewhere which causes the firmware to report a TPM2.0 chip
  # being available (which should be true based on the docs) but for some reason
  # the kernel can't use it. This disables the TPM which isn't even working
  # properly and stops it from hanging systemd for 90s on startup.
  security.tpm2.enable = false;
  boot.initrd.systemd.tpm2.enable = false;

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlP6p1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
