# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.installDeviceTree = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.deviceTree = {
    enable = true;
    name = "qcom/sc8280xp-lenovo-thinkpad-x13s.dtb";
  };

  boot.kernelParams = [
    "clk_ignore_unused"
    "pd_ignore_unused"
    "arm64.nopauth"
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "usb_storage"

    "i2c-core"
    "i2c-hid"
    "i2c-hid-of"
    "i2c-qcom-geni"
    #"pcie-qcom"
    "phy-qcom-qmp-combo"
    "phy-qcom-qmp-pcie"
    "phy-qcom-qmp-usb"
    "phy-qcom-snps-femto-v2"
    "phy-qcom-usb-hs"
  ];

  # Load the MSM GPU driver in the initrd to speed up initialization, and
  # re-set the console font via udev when the DRM device appears, since the
  # driver takeover from simpledrm resets it.
  boot.initrd.kernelModules = [ "msm" ];
  # When the MSM GPU driver takes over fb0 from simpledrm, the console font
  # is reset. Re-run vconsole-setup when the new fb device appears.
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="graphics", KERNEL=="fb[0-9]*", RUN+="${pkgs.systemd}/bin/systemctl --no-block restart systemd-vconsole-setup.service"
  '';
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # The X13s has a TPM in hardware, but Linux has no way to reach it: the device
  # tree has no TPM node, and the ACPI/FF-A path the tpm_crb_ffa driver needs
  # isn't available here. UEFI still measures boot and hands over an event log,
  # so systemd assumes a TPM exists and waits 90s for /dev/tpm0.
  #
  # Both stages need turning off. Leaving stage 1 enabled delays the switch to
  # stage 2 past the kernel's 10s deferred probe timeout, which permanently
  # fails the Adreno SMMU and takes the display controller down with it.
  systemd.tpm2.enable = false;
  boot.initrd.systemd.tpm2.enable = false;

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlP6p1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  # This box was converted back into a personal laptop, so make sure it's
  # running something easy to use and flexible.
  networking.networkmanager.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
