#! /bin/sh

. ./panel_config

sep="%{F${COLOR_DIM}}•%{F-}"

update_volume() {
    state=$(volume)
    if [ $(echo $state | cut -d ' ' -f 1) == "off" ]; then
        volume="%{F${COLOR_DIM}}♫%{F-}"
    else
        vol_percent=$(echo $state | cut -d ' ' -f 2)
        if [ $vol_percent -gt 66 ]; then
            vol_color=$COLOR_VOL3
        elif [ $vol_percent -gt 33 ]; then
            vol_color=$COLOR_VOL2
        else
            vol_color=$COLOR_VOL1
        fi
        volume="%{F$vol_color}♪ ${vol_percent}%%%{F-}"
    fi
}

update_battery() {
    batt=$(battery)
    bat_perc=$(echo $batt | cut -d ' ' -f 2)
    bat_status=$(echo $batt | cut -d ' ' -f 1)

    if [ $bat_perc -gt 75 ]; then
        bat_color=$COLOR_BAT4
    elif [ $bat_perc -gt 50 ]; then
        bat_color=$COLOR_BAT3
    elif [ $bat_perc -gt 25 ]; then
        bat_color=$COLOR_BAT2
    else
        bat_color=$COLOR_BAT1
    fi

    if [ $bat_status != "Discharging" ]; then
        bat_symbol="↑"
    else
        bat_symbol="↓"
    fi
    battery="%{F${bat_color}}${bat_symbol} ${bat_perc}%%%{F-}"
}

update_essid() {
    essid=$(essid -w wlp3s0)
    if [ "$essid" == "" ]; then
        wifi="%{F${COLOR_DIM}}N/C%{F-}"
    else
        wifi="%{F${COLOR_WIFI_UP}}${essid}%{F-}"
    fi
}

focused_desktop() {
    font=${2:-"1"}
    wm_infos="${wm_infos}%{F$COLOR_HIGHLIGHT}%{B$1}%{T$font} $name %{T0}%{B-}%{F-}"
}

desktop() {
    font=${2:-"1"}
    wm_infos="${wm_infos}%{F$1}%{T$font} $name %{T0}%{F-}"
}

while read -r line ; do
    case $line in
        V*)
            update_volume
            ;;
        C*)
            clock="${line#?}"

            update_battery
            update_volume
            update_essid
            ;;
        W*)
            wm_infos=""
            IFS=":"
            for item in ${line#?} ; do
                name=${item#?}
                case $item in
                    O*)
                        focused_desktop $COLOR_OCCUPIED "2"
                        ;;
                    F*)
                        focused_desktop $COLOR_FREE
                        ;;
                    U*)
                        focused_desktop $COLOR_URGENT "2"
                        ;;
                    o*)
                        desktop $COLOR_OCCUPIED "2"
                        ;;
                    f*)
                        desktop $COLOR_FREE
                        ;;
                    u*)
                        desktop $COLOR_URGENT "2"
                        ;;
                esac
            done
            ;;
    esac

    printf "%s\n" "%{l} $wm_infos %{c}$clock %{r}$wifi $sep $volume $sep $battery "
done
