#!/bin/sh

bspc config border_width 1
bspc config window_gap 8

bspc monitor -d I II III IV

# Visual options
bspc config split_ratio 0.5

# Config stuff
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# We don't want padding if we're on OSX as XQuartz already ignores the top bar.
if [ `uname` != "Darwin" ]
then
	bspc config top_padding 14
	killall panel &> /dev/null
	panel &> /tmp/panel.log
fi
