#!/bin/sh

bspc config border_width 1
bspc config window_gap 4

bspc monitor -d I II III IV

# Visual options
bspc config split_ratio 0.5

# Config stuff
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Colors
bspc config focused_border_color "#de935f"
bspc config normal_border_color "#373b41"
bspc config presel_border_color "#e0e0e0"

bspc config top_padding 14
#killall panel &> /dev/null
#panel &> /tmp/panel.log
