# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$python\
$character
"""

right_format = '${custom.vcs}'

add_newline = false
command_timeout = 2000

[username]
format = '[$user]($style)'
style_user = ''

[hostname]
format = '@$hostname '

[directory]
style = 'bold green'

# These two options together are a fun trick which doesn't truncate unless
# you're in a repo, in which case it truncates to the repo root.
fish_style_pwd_dir_length = 1
truncation_length = 0

[python]
format = '(\[$virtualenv\] )($style)'
style = ''

[character]
success_symbol = '[>](bold blue)'
error_symbol = '[>](bold red)'

[custom.vcs]
command = 'vcs-prompt'
when = true
format = '$output'
description = 'VCS status (jj or git)'
