{
  imports = [
    ./atticd.nix
    ./buildbot-nix.nix
    ./caddy.nix
    ./forgejo.nix
    ./forgejo-runner.nix
    ./haproxy.nix
    ./immich.nix
    ./jellyfin.nix
    ./miniflux.nix
    ./nginx.nix
    ./opencloud.nix
    ./pocket-id.nix
    ./plex.nix
    ./postgres.nix
    ./soju.nix
    ./syncthing.nix
  ];
}
