{
  imports = [
    ./atticd.nix
    ./audiobookshelf.nix
    ./btta.nix
    ./caddy.nix
    ./forgejo.nix
    ./immich.nix
    ./jellyfin.nix
    ./miniflux.nix
    ./nginx.nix
    ./pocket-id.nix
    ./plex.nix
    ./podman.nix
    ./postgres.nix
    ./soju.nix
    ./syncthing.nix
    ./woodpecker.nix
    ./woodpecker-agent.nix
  ];
}
