#!/bin/sh

bspc monitor -d I II III IV

# Visual options
bspc config top_padding 14
bspc config border_width 1
bspc config window_gap 8
bspc config split_ratio 0.5

# Config stuff
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

killall panel &> /dev/null
panel &> /tmp/panel.log
