# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  nixos-hardware,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")

    # NOTE: We actually specifically avoid the Raspberry Pi 4 modules from
    # nixos-hardware because it changes out the kernel. Sticking to mainline is
    # generally better.
    #
    #nixos-hardware.nixosModules.raspberry-pi-4
  ];

  # All of these modules seem to be needed in order to boot from a USB drive.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "uas" # usb_storage but newer
    "pcie_brcmstb" # needed for the PCIe bus to work
    "reset_raspberrypi" # needed to get the VL805 USB controller firmware to load
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/sda2";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Raspberry Pi 4 related tweaks
  console.enable = false;
  environment.systemPackages = with pkgs; [
    libraspberrypi
    raspberrypi-eeprom
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
