[colors]
background = "#000000"
foreground = "#ffffff"

# NOTE: these aren't quite right - I should probably tweak them at some
# point.
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#4d52f8"
selection_fg = "#000000"

ansi = [
  "#000000",
  "#aa0000",
  "#00aa00",
  "#aa5500",
  "#0000aa",
  "#aa00aa",
  "#00aaaa",
  "#aaaaaa",
]

brights = [
  "#555555",
  "#ff5555",
  "#55ff55",
  "#ffff55",
  "#5555ff",
  "#ff55ff",
  "#55ffff",
  "#ffffff"
]

[metadata]
aliases = []
author = "belak"
name = "Linux"
