root:
  askformore: false
  autoclip: true
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///Users/belak/.password-store
  recipient_hash: {}
  safecontent: false
  usesymbols: false
  # Disable the pager
  nopager: true
mounts: {}
version: 1.7.0-git+HEAD
